version: "3.8"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
